@startuml
    Vendeur.euse --> (Ajouter une commande)
    Vendeur.euse --> (Supprimer une commande)
    Vendeur.euse --> (Ajouter un article)
    Vendeur.euse --> (Supprimer un article)
    Vendeur.euse --> (Ajouter un utilisateur)
    Vendeur.euse --> (Supprimer un utilisateur)
    Vendeur.euse--> (Voir rapport : les plus gros acheteurs)
    Vendeur.euse --> (Voir rapport : les articles plus vendus)
    Directeur.trice --> (Ajouter un utilisateur)
    Directeur.trice --> (Supprimer un utilisateur)
    Directeur.trice --> (Voir rapport : les plus gros acheteurs)
    Directeur.trice --> (Voir rapport : les articles plus vendus)
@enduml
